### ISSUE TITLE
traceback not picklable error in child process in Python3.3 while running suites with multi-processes.

### ISSUE THREAD

**Issue by yni6** [twitter/unishark#7]
**[Precondition]**
- Python3.3
- Set multiprocessing suites in the dict config (e.g., unishark/example/config/multi-processes-tests.yaml) 
- There are failed tests (exceptions raised) in a suite and the suite is run in a child process

**[Issue]**
PicklingError: Can't pickle <class 'traceback'> is raised in the child process, which further causes concurrent.futures.process.BrokenProcessPool exception raised when get future.result().

**[Log]**
Process Process-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/multiprocessing/process.py", line 95, in run
    self._target(_self._args, *_self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/concurrent/futures/process.py", line 136, in _process_worker
    result=r))
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/multiprocessing/queues.py", line 376, in put
    return send(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/multiprocessing/connection.py", line 206, in send
    ForkingPickler(buf, pickle.HIGHEST_PROTOCOL).dump(obj)
_pickle.PicklingError: Can't pickle <class 'traceback'>: attribute lookup builtins.traceback failed

**Comment by yni6** [comment]
Fixed in commit 4aa2aa75b9f0a3bad43da6c29f0551dae627e69a
